kind: ConfigMap
apiVersion: v1
metadata:
  name: mysql-config
data:
  confluence.cnf: |-
    [mysqld]
    bind-address     = 0.0.0.0
    character-set-server=utf8
    collation-server=utf8_bin
    default-storage-engine=INNODB
    max_allowed_packet=256M
    innodb_log_file_size=2GB
    transaction-isolation=READ-COMMITTED
